name: run KexpSpotifyPlaylist

on:
  schedule:
  - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  execute-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code	
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          

      - name: install python packages
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
        
      - name: Execute Python script
        run: python KexpSpotifyPlaylist.py


        
  
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
