name: run KexpSpotifyPlaylist

on:
  schedule:
  - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  execute-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code	
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Execute Python script
        run: python KexpSpotifyPlaylist.py
        env:
          spotify_client_id: ${{ secrets.spotify_client_id }}
          spotify_secret: ${{ secrets.spotify_secret }}
          spotify_username : ${{ secrets.spotify_username }}
          redirect_url : ${{ secrets.redirect_url }}
          
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v1
